### ISSUE TITLE
Captcha Key missing

### ISSUE THREAD

**Issue by anjannair** [vigneshd332/bot-discord-random#13]
`url: "https://www.dogpile.com/serp?qc=images&q=" + search + "&capv=" + process.env.captcha_key,` in `image.js` has a captcha_key and that is not mentioned in the README file. Are you sure thats needed? Or did you forget to mention it?

Edit: I tried it on my own bot and the `captcha_key` is not required

**Comment by vigneshd332** [comment]
@anjannair That was actually to circumvent the captcha used in dogpile's image search. If the image search works without that, leave it blank, or if it doesn't, manually go to dogpile search and copy that part of the URL after `&capv=` and paste it as the captcha key. I cannot give mine is each key is associated with a user.

**Comment by anjannair** [comment]
What I meant was check your code your Key is in the code. I'm warning you that your key can be misused. Remove it from the code!!!

**Comment by vigneshd332** [comment]
@anjannair  i dont have any keys in the code, can you please specify the file and the line which youre talking about?

**Comment by anjannair** [comment]
You can close this sorry. I confused this with another issue I had opened.

**Comment by anjannair** [comment]
Closed issue sorry. I confused it with another issue I had opened on another repo. Thank you though!
