### ISSUE TITLE
ready.js does not work

### ISSUE THREAD

**Issue by ghost** [vigneshd332/bot-discord-random#15]
It does not do anything no error in terminal & nothing in terminal

**Comment by vigneshd332** [comment]
Please explain what is the problem in detail, @luxness

**Comment by ghost** [comment]
ready.js does not do anything, it doesnt set status, doesnt say signed in as bot#0000 etc  that file does not do anything

**Comment by ghost** [comment]
thats it

**Comment by vigneshd332** [comment]
@luxness It works on my end, the file you gotta run is bot.js. then ready.js gets triggered after a sucessfull login.

**Comment by vigneshd332** [comment]
are you running locally or on Heroku?

**Comment by ghost** [comment]
tried both

**Comment by vigneshd332** [comment]
It works on my end, try reinstalling everything
