### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by tahsinqp12** [vigneshd332/bot-discord-random#16]
Where I can add my bot token, prefix and other api keys?

**Comment by vigneshd332** [comment]
If its in heroku, add them in the config vars section. If it's locally, add them as environmental variables in Visual Studio Code (Google if you don't know) or if you are not using visual studio code, just replace `process.env.variable_name` with the key everywhere.

**Comment by tahsinqp12** [comment]
> If its in heroku, add them in the config vars section. If it's locally, add them as environmental variables in Visual Studio Code (Google if you don't know) or if you are not using visual studio code, just replace `process.env.variable_name` with the key everywhere.

Can you give me the code for it and tell where to place the package.(For Heroku)

**Comment by vigneshd332** [comment]
which package? there will be a place in the applications settings in Heroku
called "config vars". what to enter there is in the readme in this repo.
