### ISSUE TITLE
2 Some API issue

### ISSUE THREAD

**Issue by oakstr** [vigneshd332/bot-discord-random#18]
First of all i must say this thing is a beast. Good job. and i really appreciate all the time and effort u put into this. but only 2 modules have issues. the gif module doesn't work at all, even after i added the config var in heroku with an sdk giphy key, and a giphy api key.

other thing is the music bot part. i created 2 yt v3 api keys but the bot is just joining while playing nothing then saying "Error executing the command"

every other thing works fine

**Comment by vigneshd332** [comment]
Did you add the ffmpeg buildpack in heroku? also, post an ss of the error in the Heroku console, both with the gif and the command involving yt api

**Comment by vigneshd332** [comment]
@oakstr Did you add the ffmpeg buildpack in heroku? also, post an ss of the error in the Heroku console, both with the gif and the command involving yt api
